Remove STF banner and note that it did not pass :((
ocf/ocfweb pull request #695
Opened 2021-05-30 00:37 UTC by ethanhs

I should test this before it is merged.

2021-05-30 00:59 UTC, ja5087 approved these changes
pr: good
stf not passing: bad :(

2021-05-30 01:35 UTC, encadyma approved these changes

2021-05-30 01:37 UTC, encadyma requested changes
Thanks for making the PR. Just making sure, was the intention to fully remove the status bar or return it to normal? @ethanhs

2021-05-30 04:11 UTC, ethanhs commented
Oh I just restored it back to what it was before the STF banner. I don't have an opinion either way.

2021-06-06 00:20 UTC, encadyma approved these changes

2021-06-06 00:20 UTC, merged